In [1]:
import pandas as pd

# Day 2에서 결측치를 모두 정제 완료한 깨끗한 데이터
data = {
    '공항명': ['김포', '제주', '김해', '청주', '무안', '대구'],
    '일일이용객': [75000, 82000, 45000, 43400, 3000, 12000], 
    '지연건수': [12, 5, 8, 2, 0, 0], 
    '혼잡도': ['높음', '높음', '보통', '낮음', '낮음', '보통']
}
df = pd.DataFrame(data)

df

  공항명  일일이용객  지연건수 혼잡도
0  김포  75000    12  높음
1  제주  82000     5  높음
2  김해  45000     8  보통
3  청주  43400     2  낮음
4  무안   3000     0  낮음
5  대구  12000     0  보통

In [3]:
#'혼잡도'를 기준으로 묶어서, 숫자 데이터들의 평균 구하기
df_grouped = df.groupby('혼잡도').mean(numeric_only=True)

#결과 확인 (소수점 첫째 자리까지만 반올림)
df_grouped.round(1)

       일일이용객  지연건수
혼잡도
낮음   23200.0   1.0
높음   78500.0   8.5
보통   28500.0   4.0

### 통계 내기 필수 함수 

#### groupby() 
* 데이터를 그룹 지어주는 역할 
* 자주 쓰는 통계 함수
    * .mean() 평균
    * .sum() 합계
    * .count() 개수
    * .max()/.min() 최댓값/최솟값
    * ex.'df.groupby('항목').sum()

##### numeric_only=True 숫자로 된 데이터만 계산