In [3]:
import pandas as pd

#표1: 공항 위치 정보 데이터
info_data = {
    '공항명' : ['김포', '제주', '김해', '청주'],
    '지역' : ['수도권', '제주권', '영남권', '충청권']
}
df_info = pd.DataFrame(info_data)

#표2: DAY03에서 다뤘던 공항별 이용객 데이터 
status_data = {
    '공항명': ['김포', '제주', '김해', '무안'],
    '일일이용객' : [75000, 82000, 45000, 3000]
}
df_status = pd.DataFrame(status_data)

#두 개의 표 띄워서 눈으로 확인하기
display(df_info)
display(df_status)

  공항명   지역
0  김포  수도권
1  제주  제주권
2  김해  영남권
3  청주  충청권

  공항명  일일이용객
0  김포  75000
1  제주  82000
2  김해  45000
3  무안   3000

In [5]:
#'공항명'을 기준으로 두 데이터 프레임 병합 
# '청주' 일일이용객은 자동으로 NaN 처리 
df_merged = pd.merge(df_info, df_status, on='공항명', how='left')

#결과 확인
df_merged

  공항명   지역    일일이용객
0  김포  수도권  75000.0
1  제주  제주권  82000.0
2  김해  영남권  45000.0
3  청주  충청권      NaN

### 데이터 합치기 필수 함수

#### pd.merge() 
* VLOOKUP 기능과 동일 (가로로 병합)
* 핵심 (파라미터)
    * on='컬럼명' : 두 표를 연결할 **공통 기준**
    * how='결합방식'
        * how='left' 왼쪽 표 기준 데이터 
        * how='inner' 공통으로 존재하는 데이터