In [1]:
import pandas as pd

# 연도별 공항 이용객 가상 데이터
data = {
    '연도': [2025, 2025, 2026, 2026, 2025, 2026],
    '지역': ['수도권', '제주권', '수도권', '제주권', '영남권', '영남권'],
    '공항명': ['김포', '제주', '김포', '제주', '김해', '김해'],
    '이용객수': [70000, 80000, 75000, 82000, 40000, 45000]
}
df = pd.DataFrame(data)

df

     연도   지역 공항명   이용객수
0  2025  수도권  김포  70000
1  2025  제주권  제주  80000
2  2026  수도권  김포  75000
3  2026  제주권  제주  82000
4  2025  영남권  김해  40000
5  2026  영남권  김해  45000

In [3]:
#가로(column)는 연도, 세로(index)는 지역
#이용객수(values) 배치 

pivot_df = df.pivot_table(index='지역', columns='연도', values='이용객수')

#피벗테이블 확인
pivot_df

연도      2025     2026
지역
수도권  70000.0  75000.0
영남권  40000.0  45000.0
제주권  80000.0  82000.0

### 피벗 테이블

#### pd.pivot_table() 
* 위아래로 긴 데이터를 가로세로 교차표 형태로 변환
* **핵심 파라미터**
    * index: 세로 
    * columns: 가로
    * values: 계산 데이터