In [1]:
import pandas as pd

#텍스트가 섞여 있는 가상 공항 데이터
data = {
    '공항코드': ['SEL-GMP', 'CJU-CJU', 'PUS-PUS', 'CJJ-CJJ'],
    '운항상태': ['정상 운항', '지연 30분', '정상 운항', '결항 안내']
}
df = pd.DataFrame(data)

df

      공항코드    운항상태
0  SEL-GMP   정상 운항
1  CJU-CJU  지연 30분
2  PUS-PUS   정상 운항
3  CJJ-CJJ   결항 안내

In [2]:
#.str 기능: '공항코드'에서 앞 3글자만 추출하여 새로운 열 만들기
df['지역코드']=df['공항코드'].str[:3]

#.apply 기능: '운항상태'에서 '정상'이라는 글자가 있으면 'O' 아니면 'X' 반환
df['정상여부']=df['운항상태'].apply(lambda x: 'O' if '정상' in x else 'X')

#결과 확인
df

      공항코드    운항상태 지역코드 정상여부
0  SEL-GMP   정상 운항  SEL    O
1  CJU-CJU  지연 30분  CJU    X
2  PUS-PUS   정상 운항  PUS    O
3  CJJ-CJJ   결항 안내  CJJ    X

### 문자열 다루기와 'apply()' 함수 

#### df['열이름'].str
* 문자열 데이터의 일부분만 자르거나, 특정 단어를 다른 단어로 바꿀 때('replace')사용
* ex. df['공항코드'].str[:3]

#### df['열이름'].apply() 
* 사용자가 직접 만든 규칙이나 함수를 일괄적으로 적용 
* 'lambda'와 주로 사용 
* ex. apply(lambda x: 'O' if '정상' in x else 'X')